//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Faker.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Address {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Address() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Faker.Resources.Address", typeof(Address).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #####;####;###.
        /// </summary>
        internal static string BuildingNumber {
            get {
                return ResourceManager.GetString("BuildingNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Address.CityPrefix} {Name.First}{Address.CitySuffix};{Address.CityPrefix} {Name.First};{Name.First}{Address.CitySuffix};{Name.Last}{Address.CitySuffix}.
        /// </summary>
        internal static string CityFormat {
            get {
                return ResourceManager.GetString("CityFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to North;East;West;South;New;Lake;Port.
        /// </summary>
        internal static string CityPrefix {
            get {
                return ResourceManager.GetString("CityPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to town;ton;land;ville;berg;burgh;borough;bury;view;port;mouth;stad;furt;chester;mouth;fort;haven;side;shire.
        /// </summary>
        internal static string CitySuffix {
            get {
                return ResourceManager.GetString("CitySuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afghanistan;Albania;Algeria;American Samoa;Andorra;Angola;Anguilla;Antarctica (the territory South of 60 deg S);Antigua and Barbuda;Argentina;Armenia;Aruba;Australia;Austria;Azerbaijan;Bahamas;Bahrain;Bangladesh;Barbados;Belarus;Belgium;Belize;Benin;Bermuda;Bhutan;Bolivia;Bosnia and Herzegovina;Botswana;Bouvet Island (Bouvetoya);Brazil;British Indian Ocean Territory (Chagos Archipelago);Brunei Darussalam;Bulgaria;Burkina Faso;Burundi;Cambodia;Cameroon;Canada;Cape Verde;Cayman Islands;Central African Republi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apt. ###;Suite ###.
        /// </summary>
        internal static string SecondaryAddress {
            get {
                return ResourceManager.GetString("SecondaryAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Address.BuildingNumber} {Address.StreetName}.
        /// </summary>
        internal static string StreetAddressFormat {
            get {
                return ResourceManager.GetString("StreetAddressFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Address.BuildingNumber} {Address.StreetName} {Address.SecondaryAddress}.
        /// </summary>
        internal static string StreetAddressSecondaryFormat {
            get {
                return ResourceManager.GetString("StreetAddressSecondaryFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Name.First} {Address.StreetSuffix};{Name.Last} {Address.StreetSuffix}.
        /// </summary>
        internal static string StreetNameFormat {
            get {
                return ResourceManager.GetString("StreetNameFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  .
        /// </summary>
        internal static string StreetNameSeparator {
            get {
                return ResourceManager.GetString("StreetNameSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alley;Avenue;Branch;Bridge;Brook;Brooks;Burg;Burgs;Bypass;Camp;Canyon;Cape;Causeway;Center;Centers;Circle;Circles;Cliff;Cliffs;Club;Common;Corner;Corners;Course;Court;Courts;Cove;Coves;Creek;Crescent;Crest;Crossing;Crossroad;Curve;Dale;Dam;Divide;Drive;Drive;Drives;Estate;Estates;Expressway;Extension;Extensions;Fall;Falls;Ferry;Field;Fields;Flat;Flats;Ford;Fords;Forest;Forge;Forges;Fork;Forks;Fort;Freeway;Garden;Gardens;Gateway;Glen;Glens;Green;Greens;Grove;Groves;Harbor;Harbors;Haven;Heights;Highway;Hill;H [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StreetSuffix {
            get {
                return ResourceManager.GetString("StreetSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #####;#####-####.
        /// </summary>
        internal static string ZipCode {
            get {
                return ResourceManager.GetString("ZipCode", resourceCulture);
            }
        }
    }
}
