//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Faker.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Address {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Address() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Faker.Resources.Address", typeof(Address).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #####;####;###.
        /// </summary>
        internal static string BuildingNumber {
            get {
                return ResourceManager.GetString("BuildingNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Address.CityPrefix} {Name.First}{Address.CitySuffix};{Address.CityPrefix} {Name.First};{Name.First}{Address.CitySuffix};{Name.Last}{Address.CitySuffix}.
        /// </summary>
        internal static string CityFormat {
            get {
                return ResourceManager.GetString("CityFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to North;East;West;South;New;Lake;Port.
        /// </summary>
        internal static string CityPrefix {
            get {
                return ResourceManager.GetString("CityPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string CityRoot {
            get {
                return ResourceManager.GetString("CityRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to town;ton;land;ville;berg;burgh;borough;bury;view;port;mouth;stad;furt;chester;mouth;fort;haven;side;shire.
        /// </summary>
        internal static string CitySuffix {
            get {
                return ResourceManager.GetString("CitySuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string CommonStreetSuffixes {
            get {
                return ResourceManager.GetString("CommonStreetSuffixes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afghanistan;Albania;Algeria;American Samoa;Andorra;Angola;Anguilla;Antarctica (the territory South of 60 deg S);Antigua and Barbuda;Argentina;Armenia;Aruba;Australia;Austria;Azerbaijan;Bahamas;Bahrain;Bangladesh;Barbados;Belarus;Belgium;Belize;Benin;Bermuda;Bhutan;Bolivia;Bosnia and Herzegovina;Botswana;Bouvet Island (Bouvetoya);Brazil;British Indian Ocean Territory (Chagos Archipelago);Brunei Darussalam;Bulgaria;Burkina Faso;Burundi;Cambodia;Cameroon;Canada;Cape Verde;Cayman Islands;Central African Republi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AD;AE;AF;AG;AI;AL;AM;AO;AQ;AR;AS;AT;AU;AW;AX;AZ;BA;BB;BD;BE;BF;BG;BH;BI;BJ;BL;BM;BN;BO;BQ;BQ;BR;BS;BT;BV;BW;BY;BZ;CA;CC;CD;CF;CG;CH;CI;CK;CL;CM;CN;CO;CR;CU;CV;CW;CX;CY;CZ;DE;DJ;DK;DM;DO;DZ;EC;EE;EG;EH;ER;ES;ET;FI;FJ;FK;FM;FO;FR;GA;GB;GD;GE;GF;GG;GH;GI;GL;GM;GN;GP;GQ;GR;GS;GT;GU;GW;GY;HK;HM;HN;HR;HT;HU;ID;IE;IL;IM;IN;IO;IQ;IR;IS;IT;JE;JM;JO;JP;KE;KG;KH;KI;KM;KN;KP;KR;KW;KY;KZ;LA;LB;LC;LI;LK;LR;LS;LT;LU;LV;LY;MA;MC;MD;ME;MF;MG;MH;MK;ML;MM;MN;MO;MP;MQ;MR;MS;MT;MU;MV;MW;MX;MY;MZ;NA;NC;NE;NF;NG;NI;NL;NO;NP;NR;NU [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CountryCode {
            get {
                return ResourceManager.GetString("CountryCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to United States of America.
        /// </summary>
        internal static string DefaultCountry {
            get {
                return ResourceManager.GetString("DefaultCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apt. ###;Suite ###.
        /// </summary>
        internal static string SecondaryAddress {
            get {
                return ResourceManager.GetString("SecondaryAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alabama;Alaska;Arizona;Arkansas;California;Colorado;Connecticut;Delaware;Florida;Georgia;Hawaii;Idaho;Illinois;Indiana;Iowa;Kansas;Kentucky;Louisiana;Maine;Maryland;Massachusetts;Michigan;Minnesota;Mississippi;Missouri;Montana;Nebraska;Nevada;New Hampshire;New Jersey;New Mexico;New York;North Carolina;North Dakota;Ohio;Oklahoma;Oregon;Pennsylvania;Rhode Island;South Carolina;South Dakota;Tennessee;Texas;Utah;Vermont;Virginia;Washington;West Virginia;Wisconsin;Wyoming.
        /// </summary>
        internal static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AL;AK;AZ;AR;CA;CO;CT;DE;FL;GA;HI;ID;IL;IN;IA;KS;KY;LA;ME;MD;MA;MI;MN;MS;MO;MT;NE;NV;NH;NJ;NM;NY;NC;ND;OH;OK;OR;PA;RI;SC;SD;TN;TX;UT;VT;VA;WA;WV;WI;WY.
        /// </summary>
        internal static string StateAbbr {
            get {
                return ResourceManager.GetString("StateAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Address.BuildingNumber} {Address.StreetName}.
        /// </summary>
        internal static string StreetAddressFormat {
            get {
                return ResourceManager.GetString("StreetAddressFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Address.StreetAddress} {Address.SecondaryAddress}.
        /// </summary>
        internal static string StreetAddressSecondaryFormat {
            get {
                return ResourceManager.GetString("StreetAddressSecondaryFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Name.First} {Address.StreetSuffix};{Name.Last} {Address.StreetSuffix}.
        /// </summary>
        internal static string StreetNameFormat {
            get {
                return ResourceManager.GetString("StreetNameFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string StreetPrefix {
            get {
                return ResourceManager.GetString("StreetPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string StreetRoot {
            get {
                return ResourceManager.GetString("StreetRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alley;Avenue;Branch;Bridge;Brook;Brooks;Burg;Burgs;Bypass;Camp;Canyon;Cape;Causeway;Center;Centers;Circle;Circles;Cliff;Cliffs;Club;Common;Corner;Corners;Course;Court;Courts;Cove;Coves;Creek;Crescent;Crest;Crossing;Crossroad;Curve;Dale;Dam;Divide;Drive;Drive;Drives;Estate;Estates;Expressway;Extension;Extensions;Fall;Falls;Ferry;Field;Fields;Flat;Flats;Ford;Fords;Forest;Forge;Forges;Fork;Forks;Fort;Freeway;Garden;Gardens;Gateway;Glen;Glens;Green;Greens;Grove;Groves;Harbor;Harbors;Haven;Heights;Highway;Hill;H [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StreetSuffix {
            get {
                return ResourceManager.GetString("StreetSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pacific/Midway;Pacific/Pago_Pago;Pacific/Honolulu;America/Juneau;America/Los_Angeles;America/Tijuana;America/Denver;America/Phoenix;America/Chihuahua;America/Mazatlan;America/Chicago;America/Regina;America/Mexico_City;America/Mexico_City;America/Monterrey;America/Guatemala;America/New_York;America/Indiana/Indianapolis;America/Bogota;America/Lima;America/Lima;America/Halifax;America/Caracas;America/La_Paz;America/Santiago;America/St_Johns;America/Sao_Paulo;America/Argentina/Buenos_Aires;America/Guyana;Americ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TimeZone {
            get {
                return ResourceManager.GetString("TimeZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #####;#####-####.
        /// </summary>
        internal static string ZipCode {
            get {
                return ResourceManager.GetString("ZipCode", resourceCulture);
            }
        }
    }
}
