//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Faker.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Address {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Address() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Faker.WP71.Resources.Address", typeof(Address).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ##### {0};#### {0};### {0}.
        /// </summary>
        internal static string AddressFormat {
            get {
                return ResourceManager.GetString("AddressFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to North;East;West;South;New;Lake;Port.
        /// </summary>
        internal static string CityPrefix {
            get {
                return ResourceManager.GetString("CityPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to town;ton;land;ville;berg;burgh;borough;bury;view;port;mouth;stad;furt;chester;mouth;fort;haven;side;shire.
        /// </summary>
        internal static string CitySufix {
            get {
                return ResourceManager.GetString("CitySufix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afghanistan;Albania;Algeria;American Samoa;Andorra;Angola;Anguilla;Antarctica (the territory South of 60 deg S);Antigua and Barbuda;Argentina;Armenia;Aruba;Australia;Austria;Azerbaijan;Bahamas;Bahrain;Bangladesh;Barbados;Belarus;Belgium;Belize;Benin;Bermuda;Bhutan;Bolivia;Bosnia and Herzegovina;Botswana;Bouvet Island (Bouvetoya);Brazil;British Indian Ocean Territory (Chagos Archipelago);British Virgin Islands;Brunei Darussalam;Bulgaria;Burkina Faso;Burundi;Cambodia;Cameroon;Canada;Cape Verde;Cayman Islands; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apt. ###;Suite ###.
        /// </summary>
        internal static string SecondaryAddress {
            get {
                return ResourceManager.GetString("SecondaryAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  .
        /// </summary>
        internal static string StreetNameSeparator {
            get {
                return ResourceManager.GetString("StreetNameSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alley;Avenue;Branch;Bridge;Brook;Brooks;Burg;Burgs;Bypass;Camp;Canyon;Cape;Causeway;Center;Centers;Circle;Circles;Cliff;Cliffs;Club;Common;Corner;Corners;Course;Court;Courts;Cove;Coves;Creek;Crescent;Crest;Crossing;Crossroad;Curve;Dale;Dam;Divide;Drive;Drive;Drives;Estate;Estates;Expressway;Extension;Extensions;Fall;Falls;Ferry;Field;Fields;Flat;Flats;Ford;Fords;Forest;Forge;Forges;Fork;Forks;Fort;Freeway;Garden;Gardens;Gateway;Glen;Glens;Green;Greens;Grove;Groves;Harbor;Harbors;Haven;Heights;Highway;Hill;H [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StreetSuffix {
            get {
                return ResourceManager.GetString("StreetSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avon;Bedfordshire;Berkshire;Borders;Buckinghamshire;Cambridgeshire;Central;Cheshire;Cleveland;Clwyd;Cornwall;County Antrim;County Armagh;County Down;County Fermanagh;County Londonderry;County Tyrone;Cumbria;Derbyshire;Devon;Dorset;Dumfries and Galloway;Durham;Dyfed;East Sussex;Essex;Fife;Gloucestershire;Grampian;Greater Manchester;Gwent;Gwynedd County;Hampshire;Herefordshire;Hertfordshire;Highlands and Islands;Humberside;Isle of Wight;Kent;Lancashire;Leicestershire;Lincolnshire;Lothian;Merseyside;Mid Glamor [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UkCounties {
            get {
                return ResourceManager.GetString("UkCounties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to England;Scotland;Wales;Northern Ireland.
        /// </summary>
        internal static string UkCountry {
            get {
                return ResourceManager.GetString("UkCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ??# #??;??## #??.
        /// </summary>
        internal static string UkPostCode {
            get {
                return ResourceManager.GetString("UkPostCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alabama;Alaska;Arizona;Arkansas;California;Colorado;Connecticut;Delaware;Florida;Georgia;Hawaii;Idaho;Illinois;Indiana;Iowa;Kansas;Kentucky;Louisiana;Maine;Maryland;Massachusetts;Michigan;Minnesota;Mississippi;Missouri;Montana;Nebraska;Nevada;New Hampshire;New Jersey;New Mexico;New York;North Carolina;North Dakota;Ohio;Oklahoma;Oregon;Pennsylvania;Rhode Island;South Carolina;South Dakota;Tennessee;Texas;Utah;Vermont;Virginia;Washington;West Virginia;Wisconsin;Wyoming.
        /// </summary>
        internal static string UsState {
            get {
                return ResourceManager.GetString("UsState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AL;AK;AS;AZ;AR;CA;CO;CT;DE;DC;FM;FL;GA;GU;HI;ID;IL;IN;IA;KS;KY;LA;ME;MH;MD;MA;MI;MN;MS;MO;MT;NE;NV;NH;NJ;NM;NY;NC;ND;MP;OH;OK;OR;PW;PA;PR;RI;SC;SD;TN;TX;UT;VT;VI;VA;WA;WV;WI;WY;AE;AA;AP.
        /// </summary>
        internal static string UsStateAbbr {
            get {
                return ResourceManager.GetString("UsStateAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #####;#####-####.
        /// </summary>
        internal static string ZipCode {
            get {
                return ResourceManager.GetString("ZipCode", resourceCulture);
            }
        }
    }
}
