//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Faker.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Company {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Company() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Faker.WP71.Resources.Company", typeof(Company).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and.
        /// </summary>
        internal static string And {
            get {
                return ResourceManager.GetString("And", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to implement;utilize;integrate;streamline;optimize;evolve;transform;embrace;enable;orchestrate;leverage;reinvent;aggregate;architect;enhance;incentivize;morph;empower;envisioneer;monetize;harness;facilitate;seize;disintermediate;synergize;strategize;deploy;brand;grow;target;syndicate;synthesize;deliver;mesh;incubate;engage;maximize;benchmark;expedite;reintermediate;whiteboard;visualize;repurpose;innovate;scale;unleash;drive;extend;engineer;revolutionize;generate;exploit;transition;e-enable;iterate;cultivate;ma [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BS1 {
            get {
                return ResourceManager.GetString("BS1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to clicks-and-mortar;value-added;vertical;proactive;robust;revolutionary;scalable;leading-edge;innovative;intuitive;strategic;e-business;mission-critical;sticky;one-to-one;24/7;end-to-end;global;B2B;B2C;granular;frictionless;virtual;viral;dynamic;24/365;best-of-breed;killer;magnetic;bleeding-edge;web-enabled;interactive;dot-com;sexy;back-end;real-time;efficient;front-end;distributed;seamless;extensible;turn-key;world-class;open-source;cross-platform;cross-media;synergistic;bricks-and-clicks;out-of-the-box;ente [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BS2 {
            get {
                return ResourceManager.GetString("BS2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to synergies;web-readiness;paradigms;markets;partnerships;infrastructures;platforms;initiatives;channels;eyeballs;communities;ROI;solutions;e-tailers;e-services;action-items;portals;niches;technologies;content;vortals;supply-chains;convergence;relationships;architectures;interfaces;e-markets;e-commerce;systems;bandwidth;infomediaries;models;mindshare;deliverables;users;schemas;networks;applications;metrics;e-business;functionalities;experiences;web services;methodologies.
        /// </summary>
        internal static string BS3 {
            get {
                return ResourceManager.GetString("BS3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adaptive;Advanced;Ameliorated;Assimilated;Automated;Balanced;Business-focused;Centralized;Cloned;Compatible;Configurable;Cross-group;Cross-platform;Customer-focused;Customizable;Decentralized;De-engineered;Devolved;Digitized;Distributed;Diverse;Down-sized;Enhanced;Enterprise-wide;Ergonomic;Exclusive;Expanded;Extended;Face to face;Focused;Front-line;Fully-configurable;Function-based;Fundamental;Future-proofed;Grass-roots;Horizontal;Implemented;Innovative;Integrated;Intuitive;Inverse;Managed;Mandatory;Monitor [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Buzzwords1 {
            get {
                return ResourceManager.GetString("Buzzwords1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 24 hour;24/7;3rd generation;4th generation;5th generation;6th generation;actuating;analyzing;assymetric;asynchronous;attitude-oriented;background;bandwidth-monitored;bi-directional;bifurcated;bottom-line;clear-thinking;client-driven;client-server;coherent;cohesive;composite;context-sensitive;contextually-based;content-based;dedicated;demand-driven;didactic;directional;discrete;disintermediate;dynamic;eco-centric;empowering;encompassing;even-keeled;executive;explicit;exuding;fault-tolerant;foreground;fresh-t [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Buzzwords2 {
            get {
                return ResourceManager.GetString("Buzzwords2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ability;access;adapter;algorithm;alliance;analyzer;application;approach;architecture;archive;artificial intelligence;array;attitude;benchmark;budgetary management;capability;capacity;challenge;circuit;collaboration;complexity;concept;conglomeration;contingency;core;customer loyalty;database;data-warehouse;definition;emulation;encoding;encryption;extranet;firmware;flexibility;focus group;forecast;frame;framework;function;functionalities;Graphic Interface;groupware;Graphical User Interface;hardware;help-desk; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Buzzwords3 {
            get {
                return ResourceManager.GetString("Buzzwords3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inc and Sons;LLC;Group.
        /// </summary>
        internal static string Suffix {
            get {
                return ResourceManager.GetString("Suffix", resourceCulture);
            }
        }
    }
}
